logo: "logo.png"
title_logo: "title_logo.png"
remember_me: 1
max_name_user: 50
max_name_email: 255
max_phone: 14
min_passwd: 6
per_page: 10
per_page_book: 24
title_limit_book: 20
name_limit_book: 15
description_limit: 25
info_description_limit: 300
home_description_limit: 500
title_limit: 25
name_limit: 20
name_limit_publisher: 30
min_page_number: 10
min_current_book: 0
book_image_size: 150
type_image_accept: "image/jpeg,image/gif,image/png"
five: 5
one: 1
