logo: "logo.png"
title_logo: "title_logo.png"
user_avatar: "user.png"
author_avatar: "camera_bg.png"
remember_me: 1
max_name_user: 50
max_name_email: 255
min_comment: 10
max_phone: 14
min_passwd: 6
per_page: 30
home_title_limit_book: 45
title_limit_book: 20
name_limit_book: 15
description_limit: 25
info_description_limit: 300
home_description_limit: 500
title_limit: 25
name_limit: 20
name_limit_publisher: 30
address_limit: 30
min_page_number: 10
min_current_book: 0
book_image_size: 150
type_image_accept: "image/jpeg,image/gif,image/png"
ten: 10
five: 5
four: 4
three: 3
two: 2
one: 1
zero: 0
name: "Name"
title: "Title"
date: "Date"
char_one: "1"
char_one: "2"
char_one: "3"
char_zero: "0"
